### PR TITLE
Install requires 'zeroc-ice>=3.6.4,<3.7'

### PR DESCRIPTION
**Pull request by manics**
Travis passes: https://travis-ci.com/manics/omero-py/builds/125078136

### CODE REVIEW

**Comment by joshmoore** [comment]
As mentioned in slack, generally :+1: for this barring issues with the auto-deploy & Ice which I failed to find a fix for.

**Comment by joshmoore** [comment]
Ah, sorry. I forget this was needed with #2 or #3. I'll roll it into the version bump to 5.5.1.

**Comment by manics** [comment]
The important (ice version) commit was included in the other PRs. The docker test doesn't matter anymore.

**Comment by joshmoore** [comment]
Ok.

**Pull request closed without merging**
